apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: devops-tools
spec:
  selector:
    app: nexus
  ports:
    - name: http-ui
      port: 8081
      targetPort: 8081
    - name: docker
      port: 5000
      targetPort: 5000
