apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-cert-and-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # after cert-manager helm install
spec:
  project: default
  source:
    repoURL: https://github.com/mike-homelab/homelab-k8s-platform
    targetRevision: main
    path: clusters/homelab/apps/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true