---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-nvme
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: zfs.csi.openebs.io

allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

parameters:
  poolname: "zfspool-nvme"
  recordsize: "128k"
  compression: "lz4"
  dedup: "off"
  fsType: "zfs"

allowedTopologies:
  - matchLabelExpressions:
      - key: openebs.io/nodename
        values:
          - kubeworker01
          - kubeworker02
          - kubeworker03


---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-ssd
provisioner: zfs.csi.openebs.io

allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

parameters:
  poolname: "zfspool-ssd"
  recordsize: "128k"
  compression: "lz4"
  dedup: "off"
  fsType: "zfs"

allowedTopologies:
  - matchLabelExpressions:
      - key: openebs.io/nodename
        values:
          - kubeworker01
          - kubeworker02
          - kubeworker03

