---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-nvme
provisioner: zfs.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  poolname: zfspool-nvme
  recordsize: "128k"
  compression: "lz4"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-ssd
provisioner: zfs.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  poolname: zfspool-ssd
  recordsize: "128k"
  compression: "lz4"
