---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-nvme
provisioner: zfs.csi.openebs.io
parameters:
  poolname: "zfspool-nvme"
  recordsize: "128k"
  compression: "lz4"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true


---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-ssd
provisioner: zfs.csi.openebs.io
parameters:
  poolname: "zfspool-ssd"
  recordsize: "128k"
  compression: "lz4"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
