---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.9.3
          ports:
            - containerPort: 6333
          env:
            - name: QDRANT__LOG_LEVEL
              value: INFO

            # OpenTelemetry
            - name: OTEL_SERVICE_NAME
              value: qdrant
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.monitoring:4317
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "1Gi"

          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage

  volumeClaimTemplates:
    - metadata:
        name: qdrant-data
      spec:
        storageClassName: zfs-nvme
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
