apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-platform-configuration
  namespace: argocd
spec:
  project: ai-platform
  source:
    repoURL: https://github.com/mike-homelab/homelab-k8s-platform
    targetRevision: main
    path: homelab-k8s-platform\clusters\homelab\apps\ai-platform\configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
